### PR TITLE
Fix compat tests + run in CI

### LINKED ISSUE #43: `test-with-podman` tests don't run in CI
I just tried running `test-with-podman` tests locally and they didn't compile. I don't think the CI is currently set up to do the testing either - it probably should.

### PR DESCRIPTION
**Pull request by olivierlemasle**
# PR Content Desc

- 🩹 Bug Fix

Closes #43

## Changes proposed by this PR

- Fix compatibility tests
- Run compatibility tests in CI

## 📜 Checklist

- [x] Test coverage is excellent and passes
- [x] Works when tests are run `--all-features` enabled
- [x] Documentation is thorough

### CODE REVIEW

**Review by cmeister2 — COMMENTED** [review]
Is this test being run? I'm surprised that podman and yum commands would work on ubuntu-latest

**Comment by olivierlemasle** [comment]
`podman` is actually installed in GitHub ubuntu runner image: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#tools (I was surprised too!)

`rpm` is not needed for compat tests (`rpm`, `yum` and `dnf` are  used **inside** podman containers).

See the logs here: https://github.com/rpm-rs/rpm/actions/runs/3863408316/jobs/6585580273#step:4:419

**Comment by dralley** [comment]
Couldn't we just have the CI run inside a Fedora container instead of manually spawning podman from inside the tests?  That seems simpler.

Like [this](https://github.com/rpm-software-management/createrepo_c/blob/master/.github/workflows/ci-python.yml#L9)

**Comment by olivierlemasle** [comment]
I think the main advantages of the current solution are:
- tests are run on muliple OSes (currently `fedora:36`, `centos:stream9` and `centos:7`)
- the same integration tests can be executed easily both outside CI (just requires `cargo` and `podman`) and in CI

**Review by dralley — APPROVED** [review]

**Pull request merged**
