### PR TITLE
Remove workaround for zstd package issue, update deps

### PR DESCRIPTION
**Pull request by dralley**

### CODE REVIEW

**Review by drahnr — APPROVED** [review]

**Comment by dralley** [comment]
@drahnr I believe there are "required checks" for checks that no longer exist, but I can't seem  to find where those are configured

**Comment by dralley** [comment]
Never mind, I found it.

**Comment by dralley** [comment]
@drahnr Do we really need clippy and rustfmt running with Rust 1.59?  The outputs there shouldn't really change, the important thing is that it builds and passes tests.

**Comment by drahnr** [comment]
I don't recall why I added them, so feel free to remove after checking the commit that added them.

**Pull request merged**
