### PR TITLE
Add an empty signature constructor

### LINKED ISSUE #2: rpm-rs doesn't build with some features turned off
It should be possible to compile the codebase with `cargo build --no-default-features`. After #1 is merged, we still have the following errors:

```
error[E0599]: no function or associated item named `builder` found for struct `header::Header` in the current scope
   --> src/rpm/builder.rs:304:58
    |
304 |         let digest_header = Header::<IndexSignatureTag>::builder()
    |                                                          ^^^^^^^ function or associated item not found in `header::Header<constants::IndexSignatureTag>`
    |
   ::: src/rpm/headers/header.rs:38:1
    |
38  | pub struct Header<T: num::FromPrimitive> {
    | ---------------------------------------- function or associated item `builder` not found for this

warning: unused import: `std::io::Read`
  --> src/rpm/package.rs:17:5
   |
17 | use std::io::Read;
   |     ^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default
```

### PR DESCRIPTION
**Pull request by drahnr**
Closes #2

### CODE REVIEW

**Comment by cmeister2** [comment]
Any chance we can add an Actions step to test this in the pipelines? Running `cargo build --no-default-features` ?

**Comment by drahnr** [comment]
We should test the entire feature matrix eventually, which is a bit more work and out of scope for the PR.

Added a non default features test suite run for `+stable` only.

**Comment by drahnr** [comment]
Please rebase merge this one.

**Comment by cmeister2** [comment]
There's still a number of warnings with the new CI step. Were you expecting to resolve them as part of this or is this just to get things compiling?

https://github.com/rpm-rs/rpm/actions/runs/3547331897/jobs/5957335558#step:4:322

**Comment by cmeister2** [comment]
np. It's the sort of thing I'm happy to fix up once it's in.

**Review by cmeister2 — APPROVED** [review]
Looks good to me.

**Pull request merged**
