### PR TITLE
Fix compile error on windows

### PR DESCRIPTION
**Pull request by syokensyo**
### PR Content Desc
- Compile on Windows will fail because of file capabilities feature introduced, even thought rpm is specific for Linux, but there are may be some cross platform tools build on top of this lib(such as my developing tools for rpm package info read and display)

### 📜 Checklist

- [x] Commits are cleanly separated and have useful messages
- [x] A changelog entry or entries has been added to CHANGELOG.md
- [x] Documentation is thorough
- [x] Test coverage is excellent and passes
- [x] Works when tests are run `--all-features` enabled

### CODE REVIEW

**Comment by dralley** [comment]
@syokensyo Do you plan to undraft this?

**Comment by syokensyo** [comment]
> @syokensyo Do you plan to undraft this?

There are some file conflicts, I'll resolve it first and then submit it again.

**Comment by dralley** [comment]
@syokensyo Could you rebase and squash the commits?

**Comment by dralley** [comment]
What do you think about simply disabling the validation on Windows rather than removing the whole feature?

**Comment by syokensyo** [comment]
Yes, and capctl is platform specific, we also need some changes on it to make it work on Windows, I think that beyond the scope.

**Comment by dralley** [comment]
Ideally, the functionality for parsing capability info could be split off of the rest of the `capctl` crate, whether by feature or by splitting the actual crate, and then we could use that without pulling in the unix-specific bits.  I'm not 100% certain but from a brief skim it looks possible.  But, like you said, out of scope.

I'm thinking it is perhaps better to just store a string, and do validation via `capctl` on unix platforms where it is possible.  I don't see a great reason to lock off the feature entirely.

**Comment by dralley** [comment]
I've filed https://github.com/cptpcrd/capctl/issues/5#issue-1966380251

**Comment by dralley** [comment]
No longer an issue

**Pull request closed without merging**
