### PR TITLE
0.10.0 release

### PR DESCRIPTION
**Pull request by dralley**
Will publish on approval

### CODE REVIEW

**Comment by dralley** [comment]
Actually, I will hold out just a little bit longer, another PR ready very soon.

**Review by drahnr — COMMENTED** [review]
Cargo.lock should also contain the bump :)

Otherwise LGTM

**Comment by dralley** [comment]
This is a library so Cargo.lock isn't (and probably shouldn't be) committed.  It's in the gitignore.

**Comment by dralley** [comment]
Could you approve but NOT merge, I'll wait on https://github.com/rpm-rs/rpm/pull/133/ as well.

**Comment by dralley** [comment]
Oh, whoops.  Accident...  Must have mixed up `origin` and `upstream`...

**Comment by dralley** [comment]
Hold up... the commit isn't there though

**Comment by dralley** [comment]
wtf

**Comment by dralley** [comment]
Oohhh.  It's because this commit in question was on *my* master branch, not `upstream`, and I accidentally overwrote it on my own master branch, force-pushed it on my own master branch, and therefore it closed the PR as the commit ceased to exist

**Comment by drahnr** [comment]
I had the wtf moment too, and couldn't find the commit in history either. Thanks for clearing that up 👍

**Pull request closed without merging**
