### PR TITLE
Put build time into generated RPMs

### LINKED ISSUE #82: Add package build timestamp
Some tools have trouble with the RPMs which are built using rpm-rs, because the packages currently do not contain a build timestamp: https://github.com/cat-in-136/cargo-generate-rpm/issues/59
I propose the build timestamp be added.

In the C code for RPM, the build timestamp has type rpm_time_t which is an unsigned 32-bit integer: https://github.com/rpm-software-management/rpm/blob/master/include/rpm/rpmtypes.h and rpm-rs already partly knows about it in the form of tag constant RPMTAG_BUILDTIME, see https://github.com/rpm-rs/rpm/blob/master/src/constants.rs

Perhaps a Rust type should be added corresponding to rpm_time_t, but it can also just be handled as an u32.

### PR DESCRIPTION
**Pull request by troelsarvin**
- 🦚 Feature

Closes #82

### CODE REVIEW

**Comment by dralley** [comment]
@troelsarvin There's no need to create new PRs, you can fix up the code in the existing ones :)  If you don't know how I can help.

Could you please squash the latter two commits into the first?

**Comment by troelsarvin** [comment]
"cargo fmt" has been run now. However, I don't know how to squash commits when I have already pushed.

**Comment by dralley** [comment]
Here is a tutorial on doing it from the command line but I am sure if you are using a GUI there will be a way to do the same thing.

https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

**Comment by troelsarvin** [comment]
Thanks for the links. I found they didn't completely fit the situation where I need to rebase already-pushed commits. Now I've force-pushed the four separate commits into one. I hope that can work. Otherwise, I'll resort to sending a new, separate merge request.

**Comment by dralley** [comment]
Force pushing to your own branch is perfectly fine and is exactly what you have to do to rewrite history on a PR, so you did it correctly.

**Review by dralley — APPROVED** [review]

**Comment by dralley** [comment]
@troelsarvin Could you rebase on top of master branch?  It will fix the issue causing the CI to fail, which is unrelated to your changes.

* `git fetch $upstream-repo-remote-name` (or checkout main and git pull from the upstream)
* `git rebase master`
* `git push -f`

**Comment by dralley** [comment]
So that is technically a merge not a rebase :)  What you want to do is fetch the upstream remote, then `git rebase $upstream-remote-name`, then force-push

**Comment by troelsarvin** [comment]
I hope it's useful now.

**Review by dralley — APPROVED** [review]

**Pull request merged**
